export const ACTION_TYPES = { 

    GET_USER_TOKEN_REQUEST: "GET_USER_TOKEN_REQUEST",
    GET_USER_TOKEN_SUCCESS: "GET_USER_TOKEN_SUCCESS",
    GET_USER_TOKEN_FAILURE: "GET_USER_TOKEN_FAILURE",

    GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
    GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
    GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",
    
    LOGOUT_USER: "LOGOUT_USER",
    
    GET_REFRESH_TOKEN_SUCCESS: "GET_REFRESH_TOKEN_SUCCESS",
    GET_REFRESH_TOKEN_FAILURE: "GET_REFRESH_TOKEN_FAILURE"

};

